### ISSUE TITLE
Cura 2.4 PPA missing dependencies

### ISSUE THREAD

**Issue by tioann** [thopiekar/Cura-packaging#15]
I installed Cura 2.4 using the PPA packages on Ubuntu 16.04 (x64) but I was getting this error and no GUI:

```
2017-02-05 20:06:13,839 - DEBUG - UM.Controller.setActiveView [81]: Setting active view to SolidView
QQmlApplicationEngine failed to load component
file:///usr/share/cura/resources/qml/Cura.qml:713 Type FileDialog unavailable
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:44 module "Qt.labs.folderlistmodel" is not installed
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:45 module "Qt.labs.settings" is not installed
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:44 module "Qt.labs.folderlistmodel" is not installed
qrc:/QtQuick/Dialogs/DefaultFileDialog.qml:45 module "Qt.labs.settings" is not installed
```

I fixed it by installing a couple of packages:

```
sudo apt-get install qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel
```

**Comment by thopiekar** [comment]
Thanks @tioann !

Hmm, strange.. I was sure they were gone with 2.4.. (I'm not that familiar what changes in QML to be honest.)

There are two possibilities:
1. You fix it by making changes based on the 2.4 branch, send a PR and I merge it into 2.4 itself + master, too.
2. I prepare it tomorrow.

Have to pack my things and go to bed soon.

Regards and thanks again!
