### ISSUE TITLE
Remove dependency on dh-python

### ISSUE THREAD

**Issue by onitake** [thopiekar/Cura-packaging#2]
I am by no means an expert, but I noticed that dpkg would generate (empty) python- packages alongside the python3- ones when dh-python is among the build dependencies. That doesn't make a lot of sense, as Python 2 is not supported by Uranium and libArcus.

Apparently, it suffices to simply depend on python3. The build system is cmake anyway.

**Comment by onitake** [comment]
It looks like this dependency is required.
If the build system and other dependencies are specified correctly, debhelper will not try to build python2 packages.

**Comment by thopiekar** [comment]
Nope, you are actually right. By passing ```--buildsystem=cmake``` you override the usage of `dh_python`.
I'm sure dh_python is superfluous here, but I'm currently to busy to check that.

**Comment by onitake** [comment]
Interesting... Though, at it least it does no harm, if buildsystem is specified.
I'll leave it aside for now, it is a minor issue without any user impact.
