### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by jgreth** [thopiekar/Cura-packaging#22]
When trying to install Cura 2.5 Plugins via "`sudo apt install cura-plugins-all`" on Ubuntu 16.04 x64 i get:
```
cura-plugins-all : Hängt ab von: cura-plugin-pausebackend ist aber nicht installierbar
```
(cura-plugins-all : depends on: cura-plugin-pausebackend which is not installable)

When i then try to install manually via "`sudo apt install cura-plugin-pausebackend`" i get:
```
Paket cura-plugin-pausebackend ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.
E: Für Paket »cura-plugin-pausebackend« existiert kein Installationskandidat.
```
Packet cura-plugin-pausebackend is not available but reference by antoher packet.
It can be missing, replaced by antoher or is only available from antoher source.
E: For packet »cura-plugin-pausebackend« exists no Installationcandidate.

@thopiekar Can you tell what's wrong here?

**Comment by thopiekar** [comment]
Forgot to update the meta-package. After approx a day the update should be there and the problem fixed 😉
