### ISSUE TITLE
Cura crashes when selecting a multi extruder machine

### ISSUE THREAD

**Issue by maukcc** [thopiekar/Cura-packaging#26]
The current version of this Cura (master) ppa is still 2.6.99.
We are having a problem when selecting a machine with multiple extruders, that the program crashes.
See https://github.com/Ultimaker/Cura/issues/2243#issuecomment-324462169
In the 2.7 appimage this is not present anymore.

**Comment by thopiekar** [comment]
The packages you are using are also build from master and not from 2.7.
Could be that the fix is in 2.7 only and not merged into master.

However, you are using master builds and I'm too busy to fix it now.

**Comment by maukcc** [comment]
OK, thanks for the update.
This can be closed then.
