### ISSUE TITLE
Cura will only load ascii .stl files

### ISSUE THREAD

**Issue by maukcc** [thopiekar/Cura-packaging#38]
Cura will only load ascii .stl files, binary .stl files generate an error.

[dualXYtest1_ascii.stl.txt](https://github.com/thopiekar/Cura-packaging/files/1740196/dualXYtest1_ascii.stl.txt)
[dualXYtest1_binary.stl.txt](https://github.com/thopiekar/Cura-packaging/files/1740198/dualXYtest1_binary.stl.txt)

**Comment by thopiekar** [comment]
I guess this is due to missing Numpy-STL package.
But it is available in upstream as: python3-stl
https://github.com/thopiekar/Cura-packaging/commit/45ce9ce0567acfd82ffbe78c35874545ecca3eb2

**Comment by Ghostkeeper** [comment]
Unable to reproduce. I've disabled the numpy-stl package running from source, but the back-up still loaded binary STL files fine.

**Comment by maukcc** [comment]
Did I make a mistake here? because I too can open the binary file, but not the ascii files.
@Ghostkeeper : can you try the ascii file as well?

**Comment by Ghostkeeper** [comment]
The ASCII file also works for me, at least in the current state of Master.

![screenshot from 2018-04-11 09-56-22](https://user-images.githubusercontent.com/2448634/38603702-a4adf374-3d6e-11e8-88b9-360a9f8909ea.png)

**Comment by maukcc** [comment]
Yes, binary files can be loaded, ascii files can not.

**Comment by thopiekar** [comment]
Maybe related :question: 
https://github.com/Ultimaker/Uranium/pull/393

**Comment by maukcc** [comment]
This is still present.
I removed Cura and  installed from the debian repositories (3.1) and that worked.
Then updated to the stable version of this ppa and lost the ability to load the .stl files
The only change I noticed apart from adding a bunch of new files was the deletion of libpolyclipping22.
Maybe that has something to do with it ?

**Comment by thopiekar** [comment]
Well, I think it is not slicing because of #50 
Has been a long time ago since I made my last slice on my Linux installation.

**Comment by thopiekar** [comment]
Found also issues with the STLReader. For some reason the NumPy-STL module fails to read files.
Maybe the NumPy-STL package in Ubuntu is outdated.

However, added a workaround to STLReader to be able to fallback.

PR will follow soon.
