### ISSUE TITLE
Octoprint plugin crashes Cura

### ISSUE THREAD

**Issue by maukcc** [thopiekar/Cura-packaging#39]
The plugin install correct but, when trying to connect, Cura crashes
Here is the log
[cura.log](https://github.com/thopiekar/Cura-packaging/files/1743410/cura.log)

**Comment by thopiekar** [comment]
@fieldOfView FYI
@maukcc I don't see any reference to an old plugin package, but did you make sure all 3rd-party plugins are removed from apt/dpkg?

**Comment by fieldOfView** [comment]
If you use the master branch of Cura, you must also use the master banch of the OctoPrintPlugin

**Comment by thopiekar** [comment]
@maukcc: Based on @fieldOfView 's info, please remove cura and all dependencies from the master PPA and install Cura from the stable PPA again.

**Comment by maukcc** [comment]
Using the master branch of OctoPrintPlugin worked.
I am just not seeing the video feed
