### ISSUE TITLE
cura 2.3

### ISSUE THREAD

**Issue by dmstan** [thopiekar/Cura-packaging#4]
tried installing cura 2.3 using the ppa, but gives me the folowing error:
An uncaught exception has occurred!
Traceback (most recent call last):
  File "/usr/bin/cura", line 47, in <module>
    import Arcus #@UnusedImport
RuntimeError: the sip module implements API v11.0 to v11.2 but the Arcus module requires API v11.3
Any idea how to solve it?
Running Linux Mint 18 Cinnamon 64-bit
Thank you

**Comment by thopiekar** [comment]
Hey @dmstan, looks for me like you've mixed up your installation.
The table here (https://www.linuxmint.com/download_all.php) says that Mint 18 is equivalent to Ubuntu Xenial. Is APT using Xenial, too?
Another possible reason could be that the Mint developers replaced the SIP with a newer version in their software repository.

**Comment by dmstan** [comment]
I tried previously to install Cura-2.1.2-Linux.deb, version 2.1.3 deb and 2.3 deb from Ultimaker web-site. Maybe that mixed up stuff. Not sure how to fix.

**Comment by thopiekar** [comment]
You'll need to remove their package first. You can take synaptic for this. Reitstall cura again and remove your config to be sure.

**Comment by thopiekar** [comment]
I guess you managed to fix it.
