### ISSUE TITLE
Well done! Canonical broke the PPA again!

### ISSUE THREAD

**Issue by thopiekar** [thopiekar/Cura-packaging#41]
@onitake: Canonical switched to PyQt5 5.10. Any experiences with it?

Additionally contacted the PyQt5 maintainer for help via email.

**Comment by thopiekar** [comment]
Good news: https://bugs.launchpad.net/ubuntu/+source/pyqt5/+bug/1766092

**Comment by thopiekar** [comment]
.. and works with the new patch again. :champagne:

**Comment by onitake** [comment]
Yeah, I hit that same problem a little later than you.
But the PyQt5 patch was accepted into Debian very quickly, so it wasn't an issue for very long.
Thanks for the heads up!

**Comment by thopiekar** [comment]
No problem. Remember that it was quite funny. I took some time finally and fixed the packaging files, so Cura was running agauin. But after 3 days the PyQt5 update came in and broke it again 😂

However, runs well now. Have you noticed the stb packaging files? You will need it for future CuraEngine builds.

**Comment by onitake** [comment]
No, not yet.
Haven't noticed it in 3.3, I guess it will be in 3.4?
Great, another new library to package...
I'm guessing it's this one here: https://github.com/nothings/stb

**Comment by thopiekar** [comment]
Yes, that one is new. Either for 3.4 or 3.5. To be honest I am too busy to keep the stable PPA up-to-date. Will maybe update it this weekend.
