### ISSUE TITLE
Stable PPA builds failing for cura-engine

### ISSUE THREAD

**Issue by neildarlow** [thopiekar/Cura-packaging#53]
Hi,

The latest stable packaging of Cura is version 3.4.1 (currently released is version 3.5.1). There have been no later versions packaged since cura-engine builds started failing 11 weeks ago.

**Comment by thopiekar** [comment]
Hmm, I'll go up to 3.5.x soon.
Need to fix the master builds before..

There was a problem with the engine before and was hoping I could get a fix through at Ultimaker.
However, it got forgotten and I was too busy to follow up and remind them.

**Comment by neildarlow** [comment]
Thank you Thomas. Excellent work getting 3.6.0 packaged.

**Comment by thopiekar** [comment]
Always a pleasure!
