### ISSUE TITLE
Optional: Adding PPA for Cura 3.x series

### ISSUE THREAD

**Issue by rkosnar** [thopiekar/Cura-packaging#60]
There is same dependency issue on ppa:thopiekar/cura-master related to #59

Is it possible to reoffer Cura v 3.6 for Ubuntu 18.04?

**Comment by thopiekar** [comment]
Well, you can take a look at #55 why a downgrade is no option for me.
If 3.6 wouldn't be a problematic version, I would take the effort. But investing time in another PPA with 3.6 with bugs is not worth it, I think.

**Comment by rkosnar** [comment]
I known about 55. I guess it should be possible to roll back before this bug - that version works great. For me it is not possible to use non LTS version of ubuntu right now.
