### ISSUE TITLE
Cura Stable 4.8.0 have no cloud backup option

### ISSUE THREAD

**Issue by ColdBeer72** [thopiekar/Cura-packaging#77]
As on Windows, once you are logged to Ultimaker Cura, you could automatically sync your plugins, but on Linux you can't make a thing doesn't need any plugin (just need you've been logged): BACKUP and RESTORE your configuration.

I would love to use it as I work on different computers in my home.

**Comment by thopiekar** [comment]
I'm not sure whether I clearly understand your request here. You are asking to develop a plugin for your needs?
