### ISSUE TITLE
/usr/lib/libgeos_c.so missing and uninstallable on Ubuntu

### ISSUE THREAD

**Issue by ryneches** [thopiekar/Cura-packaging#78]
Cura fails to start on hirsute due to missing dependency (/usr/lib/libgeos_c.so). Ubuntu does not maintain any package that provides this file at this path. libgeos-dev installs it under /usr/lib/x86_64-linux-gnu/ on x86 systems.

**Comment by thopiekar** [comment]
Interesting. Do you know which component of Cura needs it? E.g. libSavitar? Whatever else?

**Comment by thopiekar** [comment]
Additionally, I double-checked in the mean time and it works perfectly fine.
I'm closing this, but feel free to share more info if the problem persists.

**Comment by Ghostkeeper** [comment]
Geos is a dependency of Shapely, which is used for convex hull calculation.
