### ISSUE TITLE
Stable ppa should be 4.9+ already but still 4.8

### ISSUE THREAD

**Issue by darkblaze69** [thopiekar/Cura-packaging#79]
Stable ppa should be 4.9+ already but still 4.8

**Comment by manu-p** [comment]
Cura is currently 4.10, any plan to package this latest version? Thanks

**Comment by fpitters** [comment]
I've noticed there is a different ppa labelled as "Cura master" that I guess is more a Dev/Beta channel?
I'll give it a try
