### ISSUE TITLE
Can't import SLDPRT if solidworks is running

### ISSUE THREAD

**Issue by JiMcNulty** [thopiekar/Cura-packaging#80]
https://github.com/Ultimaker/Cura/issues/11079

**Comment by Ghostkeeper** [comment]
This repository is about a packaging script to package Cura for Debian. It has nothing to do with Solidworks integration. I think you're looking for [this](https://git.thopiekar.eu/Cura/CAD/CuraSolidworksPlugin/-/issues).

**Comment by thopiekar** [comment]
or this: https://thopiekar.eu/about/contact/
